---
abstract: 'API client for NHK program API'
author:
  - 'moznion <moznion@gmail.com>'
build_requires:
  Scope::Guard: 0
  Test::Deep: 0
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.11.0, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-NHKProgram-API
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  WWW::NHKProgram::API:
    file: lib/WWW/NHKProgram/API.pm
    version: 0.01
  WWW::NHKProgram::API::Area:
    file: lib/WWW/NHKProgram/API/Area.pm
  WWW::NHKProgram::API::Date:
    file: lib/WWW/NHKProgram/API/Date.pm
  WWW::NHKProgram::API::Provider:
    file: lib/WWW/NHKProgram/API/Provider.pm
  WWW::NHKProgram::API::Provider::Common:
    file: lib/WWW/NHKProgram/API/Provider/Common.pm
  WWW::NHKProgram::API::Provider::Genre:
    file: lib/WWW/NHKProgram/API/Provider/Genre.pm
  WWW::NHKProgram::API::Provider::Info:
    file: lib/WWW/NHKProgram/API/Provider/Info.pm
  WWW::NHKProgram::API::Provider::List:
    file: lib/WWW/NHKProgram/API/Provider/List.pm
  WWW::NHKProgram::API::Provider::Now:
    file: lib/WWW/NHKProgram/API/Provider/Now.pm
  WWW::NHKProgram::API::Service:
    file: lib/WWW/NHKProgram/API/Service.pm
requires:
  Class::Accessor::Lite::Lazy: 0
  Encode: 0
  Furl: 0
  JSON: 0
  Text::Sprintf::Named: 0
  parent: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/moznion/WWW-NHKProgram-API/issues
  homepage: https://github.com/moznion/WWW-NHKProgram-API
  repository: git://github.com/moznion/WWW-NHKProgram-API.git
version: 0.01
